name: Building the project
run-name: ${{ github.actor }} is testing the project
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v1
      with:
        version: 1.0.1
    - run: bun install
    - run: bun test
